#ifndef RADII_BOOTLOADER_SIMPLE_FILE_SYSTEM_PROTOCOL_H
#define RADII_BOOTLOADER_SIMPLE_FILE_SYSTEM_PROTOCOL_H

#include "types.h"
#include "file_protocol.h"

#define EFI_SIMPLE_FILE_SYSTEM_PROTOCOL_GUID \
 {0x0964e5b22,0x6459,0x11d2, {0x8e,0x39,0x00,0xa0,0xc9,0x69,0x72,0x3b}}

#define EFI_SIMPLE_FILE_SYSTEM_PROTOCOL_REVISION 0x00010000

typedef struct EFI_SIMPLE_FILE_SYSTEM_PROTOCOL {
  UINT64 Revision;
  EFI_STATUS (*OpenVolume)(struct EFI_SIMPLE_FILE_SYSTEM_PROTOCOL *This
                           , EFI_FILE_PROTOCOL **Root);
} EFI_SIMPLE_FILE_SYSTEM_PROTOCOL;

#endif /* RADII_BOOTLOADER_SIMPLE_FILE_SYSTEM_PROTOCOL_H */
