#ifndef RADII_BOOTLOADER_FILE_OPERATIONS_H
#define RADII_BOOTLOADER_FILE_OPERATIONS_H

#include <efi.h>

EFI_STATUS LoadFileAtPath(CHAR16 *Path, EFI_FILE *File, EFI_FILE *Directory);

#endif /* RADII_BOOTLOADER_FILE_OPERATIONS_H */
