#ifndef RADII_BOOTLOADER_FILE_OPERATIONS_H
#define RADII_BOOTLOADER_FILE_OPERATIONS_H

#include <EFI/efi.h>

EFI_FILE* LoadFileAtPath(EFI_FILE *Directory, CHAR16 *Path);

#endif /* RADII_BOOTLOADER_FILE_OPERATIONS_H */
